// Recomended Jobs
const recomendedjob = [
    {
        id: '1',
        position: 'Assistant / Store Keeper',
        c_name: 'Moetic Fashion',
        location: 'Limestone, US',
        salary: '$340 - $800',
        experience: '0-3 year',
        job_type: 'Intership'
    },
    {
        id: '2',
        position: 'Education Training',
        c_name: 'Micro Design',
        location: 'Germany',
        salary: '$750 - $940',
        experience: '1.5+ year',
        job_type: 'Freelancer'
    },
    {
        id: '3',
        position: 'Executive, HR Operations',
        c_name: 'Micro Design',
        location: 'Texanna, US',
        salary: '$50 - $120',
        experience: '1-5 year',
        job_type: 'Part Time'
    },
    {
        id: '4',
        position: 'Full Stack Engineer',
        c_name: 'Syntyce Solutions',
        location: 'Zuweihir, UAE',
        salary: '$650 - $900',
        experience: '0-1+ year',
        job_type: 'Full Time'
    },
    {
        id: '5',
        position: 'Full Stack Engineer',
        c_name: 'Force Medicines',
        location: 'Ugashik, US',
        salary: '$120 - $180',
        experience: '2-5 year',
        job_type: 'Part Time'
    },
    {
        id: '6',
        position: 'Full Stack Engineer',
        c_name: 'Digitech Galaxy',
        location: 'Maidaq, UAE',
        salary: '$900 - $1020',
        experience: '3-5 year',
        job_type: 'Full Time'
    },
    {
        id: '7',
        position: 'Graphic Designer',
        c_name: 'Digitech Galaxy',
        location: 'Mughairah, UAE',
        salary: '$160 - $230',
        experience: '2-3+ year',
        job_type: 'Full Time'
    },
    {
        id: '8',
        position: 'Marketing Director',
        c_name: 'Meta4Systems',
        location: 'Vinninga, Sweden',
        salary: '$250 - $800',
        experience: '0-5 year',
        job_type: 'Full Time'
    },
    {
        id: '9',
        position: 'Marketing Director',
        c_name: 'Zoetic Fashion',
        location: 'Quesada, US',
        salary: '$600 - $870',
        experience: '0-5 year',
        job_type: 'Freelancer'
    },
    {
        id: '10',
        position: 'Project Manager',
        c_name: 'Themesbrand',
        location: 'California, US',
        salary: '$400 - $600',
        experience: '3+ year',
        job_type: 'Part Time'
    },
    {
        id: '11',
        position: 'Project Manager',
        c_name: 'Meta4Systems',
        location: 'Limestone, US',
        salary: '$210 - $300',
        experience: '0-2+ year',
        job_type: 'Freelancer'
    },
    {
        id: '12',
        position: 'React Developer',
        c_name: 'iTest Factory',
        location: 'Khabākhib, UAE',
        salary: '$90 - $160',
        experience: '5+ year',
        job_type: 'Intership'
    },
    {
        id: '13',
        position: 'UI/UX designer',
        c_name: 'Zoetic Fashion',
        location: 'Cullera, Spain',
        salary: '$400+',
        experience: '0-2 year',
        job_type: 'Part Time'
    },
    {
        id: '14',
        position: 'Web Designer',
        c_name: 'Force Medicines',
        location: 'Ugashik, US',
        salary: '$412 - $241',
        experience: '3+ year',
        job_type: 'Freelancer'
    }
]

// Popular Candidate
const candidate = [
    {
        id: '1',
        image: 'assets/images/users/avatar-10.jpg',
        name: 'Tonya Noble',
        insta: 'tonya',
        designation: 'Web Developer'
    },
    {
        id: '2',
        image: 'assets/images/users/avatar-1.jpg',
        name: 'Nicholas Ball',
        insta: 'nicholas',
        designation: 'Assistant / Store Keeper'
    },
    {
        id: '3',
        image: 'assets/images/users/avatar-9.jpg',
        name: 'Zynthia Marrow',
        insta: 'zynthia',
        designation: 'Full Stack Engineer'
    },
    {
        id: '4',
        image: 'assets/images/users/avatar-2.jpg',
        name: 'Cheryl Moore',
        insta: 'Cheryl',
        designation: 'Product Designer'
    },
    {
        id: '5',
        image: 'assets/images/users/avatar-5.jpg',
        name: 'Jennifer Bailey',
        insta: 'Jennifer',
        designation: 'Marketing Director'
    },
    {
        id: '6',
        image: 'assets/images/users/avatar-8.jpg',
        name: 'Hadley Leonard',
        insta: 'hadley',
        designation: 'Executive, HR Operations'
    }
]

export const SuiviAbonne = [
    {
      id_fait: BigInt(1),
      id_abonne: BigInt(1),
      id_directions: BigInt(12),
      id_produit: BigInt(1),
      id_temps: "2020-02-28",
      nombre_total_abonnes: BigInt(1),
      abonnes_actifs: BigInt(1),
      abonnes_forfait: BigInt(0),
      nouveaux_abonnes: BigInt(1),
      abonnes_factures: BigInt(0),
      abonnes_resilies: BigInt(0),
      nombre_resiliation: BigInt(0),
      nombre_modification_ps: BigInt(0),
      nombre_migration: BigInt(0),
      nombre_suspension: BigInt(0)
    },
    {
      id_fait: BigInt(2),
      id_abonne: BigInt(2),
      id_directions: BigInt(12),
      id_produit: BigInt(1),
      id_temps: "2020-02-28",
      nombre_total_abonnes: BigInt(1),
      abonnes_actifs: BigInt(1),
      abonnes_forfait: BigInt(0),
      nouveaux_abonnes: BigInt(1),
      abonnes_factures: BigInt(0),
      abonnes_resilies: BigInt(0),
      nombre_resiliation: BigInt(0),
      nombre_modification_ps: BigInt(0),
      nombre_migration: BigInt(0),
      nombre_suspension: BigInt(0)
    },
    {
      id_fait: BigInt(3),
      id_abonne: BigInt(3),
      id_directions: BigInt(12),
      id_produit: BigInt(2),
      id_temps: "2020-03-03",
      nombre_total_abonnes: BigInt(1),
      abonnes_actifs: BigInt(1),
      abonnes_forfait: BigInt(0),
      nouveaux_abonnes: BigInt(1),
      abonnes_factures: BigInt(0),
      abonnes_resilies: BigInt(0),
      nombre_resiliation: BigInt(0),
      nombre_modification_ps: BigInt(0),
      nombre_migration: BigInt(0),
      nombre_suspension: BigInt(0)
    },
    {
      id_fait: BigInt(4),
      id_abonne: BigInt(4),
      id_directions: BigInt(12),
      id_produit: BigInt(1),
      id_temps: "2020-02-28",
      nombre_total_abonnes: BigInt(1),
      abonnes_actifs: BigInt(0),
      abonnes_forfait: BigInt(0),
      nouveaux_abonnes: BigInt(1),
      abonnes_factures: BigInt(0),
      abonnes_resilies: BigInt(0),
      nombre_resiliation: BigInt(0),
      nombre_modification_ps: BigInt(0),
      nombre_migration: BigInt(0),
      nombre_suspension: BigInt(0)
    },
    {
      id_fait: BigInt(5),
      id_abonne: BigInt(5),
      id_directions: BigInt(12),
      id_produit: BigInt(2),
      id_temps: "2020-03-03",
      nombre_total_abonnes: BigInt(1),
      abonnes_actifs: BigInt(1),
      abonnes_forfait: BigInt(0),
      nouveaux_abonnes: BigInt(1),
      abonnes_factures: BigInt(0),
      abonnes_resilies: BigInt(0),
      nombre_resiliation: BigInt(0),
      nombre_modification_ps: BigInt(0),
      nombre_migration: BigInt(0),
      nombre_suspension: BigInt(0)
    },
    {
      id_fait: BigInt(6),
      id_abonne: BigInt(6),
      id_directions: BigInt(12),
      id_produit: BigInt(2),
      id_temps: "2020-03-03",
      nombre_total_abonnes: BigInt(1),
      abonnes_actifs: BigInt(0),
      abonnes_forfait: BigInt(0),
      nouveaux_abonnes: BigInt(1),
      abonnes_factures: BigInt(1),
      abonnes_resilies: BigInt(0),
      nombre_resiliation: BigInt(1),
      nombre_modification_ps: BigInt(0),
      nombre_migration: BigInt(0),
      nombre_suspension: BigInt(0)
    },
    {
      id_fait: BigInt(7),
      id_abonne: BigInt(7),
      id_directions: BigInt(12),
      id_produit: BigInt(2),
      id_temps: "2020-02-28",
      nombre_total_abonnes: BigInt(1),
      abonnes_actifs: BigInt(0),
      abonnes_forfait: BigInt(0),
      nouveaux_abonnes: BigInt(1),
      abonnes_factures: BigInt(0),
      abonnes_resilies: BigInt(0),
      nombre_resiliation: BigInt(0),
      nombre_modification_ps: BigInt(0),
      nombre_migration: BigInt(0),
      nombre_suspension: BigInt(1)
    },
    {
      id_fait: BigInt(8),
      id_abonne: BigInt(8),
      id_directions: BigInt(9),
      id_produit: BigInt(1),
      id_temps: "2020-03-03",
      nombre_total_abonnes: BigInt(1),
      abonnes_actifs: BigInt(1),
      abonnes_forfait: BigInt(0),
      nouveaux_abonnes: BigInt(1),
      abonnes_factures: BigInt(0),
      abonnes_resilies: BigInt(0),
      nombre_resiliation: BigInt(0),
      nombre_modification_ps: BigInt(0),
      nombre_migration: BigInt(0),
      nombre_suspension: BigInt(0)
    },
    {
      id_fait: BigInt(9),
      id_abonne: BigInt(9),
      id_directions: BigInt(9),
      id_produit: BigInt(2),
      id_temps: "2020-02-28",
      nombre_total_abonnes: BigInt(1),
      abonnes_actifs: BigInt(1),
      abonnes_forfait: BigInt(0),
      nouveaux_abonnes: BigInt(1),
      abonnes_factures: BigInt(0),
      abonnes_resilies: BigInt(0),
      nombre_resiliation: BigInt(0),
      nombre_modification_ps: BigInt(0),
      nombre_migration: BigInt(0),
      nombre_suspension: BigInt(0)
    },
    {
      id_fait: BigInt(10),
      id_abonne: BigInt(10),
      id_directions: BigInt(9),
      id_produit: BigInt(2),
      id_temps: "2020-03-03",
      nombre_total_abonnes: BigInt(1),
      abonnes_actifs: BigInt(0),
      abonnes_forfait: BigInt(0),
      nouveaux_abonnes: BigInt(1),
      abonnes_factures: BigInt(0),
      abonnes_resilies: BigInt(0),
      nombre_resiliation: BigInt(0),
      nombre_modification_ps: BigInt(1),
      nombre_migration: BigInt(0),
      nombre_suspension: BigInt(0)
    },
    {
      id_fait: BigInt(11),
      id_abonne: BigInt(11),
      id_directions: BigInt(9),
      id_produit: BigInt(2),
      id_temps: "2020-03-19",
      nombre_total_abonnes: BigInt(1),
      abonnes_actifs: BigInt(1),
      abonnes_forfait: BigInt(0),
      nouveaux_abonnes: BigInt(1),
      abonnes_factures: BigInt(0),
      abonnes_resilies: BigInt(0),
      nombre_resiliation: BigInt(0),
      nombre_modification_ps: BigInt(0),
      nombre_migration: BigInt(0),
      nombre_suspension: BigInt(0)
    },
    {
      id_fait: BigInt(12),
      id_abonne: BigInt(12),
      id_directions: BigInt(9),
      id_produit: BigInt(1),
      id_temps: "2020-03-03",
      nombre_total_abonnes: BigInt(1),
      abonnes_actifs: BigInt(1),
      abonnes_forfait: BigInt(0),
      nouveaux_abonnes: BigInt(1),
      abonnes_factures: BigInt(0),
      abonnes_resilies: BigInt(0),
      nombre_resiliation: BigInt(0),
      nombre_modification_ps: BigInt(0),
      nombre_migration: BigInt(0),
      nombre_suspension: BigInt(0)
    },
    {
      id_fait: BigInt(13),
      id_abonne: BigInt(13),
      id_directions: BigInt(9),
      id_produit: BigInt(1),
      id_temps: "2020-02-28",
      nombre_total_abonnes: BigInt(1),
      abonnes_actifs: BigInt(0),
      abonnes_forfait: BigInt(0),
      nouveaux_abonnes: BigInt(1),
      abonnes_factures: BigInt(0),
      abonnes_resilies: BigInt(0),
      nombre_resiliation: BigInt(0),
      nombre_modification_ps: BigInt(0),
      nombre_migration: BigInt(0),
      nombre_suspension: BigInt(0)
    },
    {
      id_fait: BigInt(14),
      id_abonne: BigInt(14),
      id_directions: BigInt(9),
      id_produit: BigInt(1),
      id_temps: "2020-03-19",
      nombre_total_abonnes: BigInt(1),
      abonnes_actifs: BigInt(0),
      abonnes_forfait: BigInt(0),
      nouveaux_abonnes: BigInt(1),
      abonnes_factures: BigInt(0),
      abonnes_resilies: BigInt(0),
      nombre_resiliation: BigInt(0),
      nombre_modification_ps: BigInt(1),
      nombre_migration: BigInt(0),
      nombre_suspension: BigInt(0)
    },
    {
        id_fait: BigInt(15),
        id_abonne: BigInt(15),
        id_directions: BigInt(10),
        id_produit: BigInt(2),
        id_temps: "2020-02-28",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(1),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(16),
        id_abonne: BigInt(16),
        id_directions: BigInt(10),
        id_produit: BigInt(2),
        id_temps: "2020-03-03",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(0),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(1),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(17),
        id_abonne: BigInt(17),
        id_directions: BigInt(10),
        id_produit: BigInt(2),
        id_temps: "2020-03-19",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(0),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(18),
        id_abonne: BigInt(18),
        id_directions: BigInt(10),
        id_produit: BigInt(2),
        id_temps: "2020-02-28",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(1),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(19),
        id_abonne: BigInt(19),
        id_directions: BigInt(10),
        id_produit: BigInt(1),
        id_temps: "2020-03-19",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(0),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(1),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(20),
        id_abonne: BigInt(20),
        id_directions: BigInt(10),
        id_produit: BigInt(2),
        id_temps: "2020-03-03",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(0),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(1),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(1),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(21),
        id_abonne: BigInt(21),
        id_directions: BigInt(10),
        id_produit: BigInt(2),
        id_temps: "2020-03-19",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(1),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(22),
        id_abonne: BigInt(22),
        id_directions: BigInt(10),
        id_produit: BigInt(2),
        id_temps: "2020-03-03",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(1),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(23),
        id_abonne: BigInt(23),
        id_directions: BigInt(11),
        id_produit: BigInt(2),
        id_temps: "2020-03-19",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(0),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(1),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(24),
        id_abonne: BigInt(24),
        id_directions: BigInt(11),
        id_produit: BigInt(1),
        id_temps: "2020-03-03",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(1),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(25),
        id_abonne: BigInt(25),
        id_directions: BigInt(11),
        id_produit: BigInt(1),
        id_temps: "2020-03-19",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(0),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(1),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(26),
        id_abonne: BigInt(26),
        id_directions: BigInt(11),
        id_produit: BigInt(1),
        id_temps: "2020-02-28",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(1),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(27),
        id_abonne: BigInt(27),
        id_directions: BigInt(11),
        id_produit: BigInt(1),
        id_temps: "2020-02-28",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(0),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(28),
        id_abonne: BigInt(28),
        id_directions: BigInt(11),
        id_produit: BigInt(1),
        id_temps: "2020-03-19",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(1),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(29),
        id_abonne: BigInt(29),
        id_directions: BigInt(11),
        id_produit: BigInt(1),
        id_temps: "2020-03-19",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(0),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(1),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(30),
        id_abonne: BigInt(30),
        id_directions: BigInt(11),
        id_produit: BigInt(2),
        id_temps: "2020-02-28",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(0),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(31),
        id_abonne: BigInt(31),
        id_directions: BigInt(11),
        id_produit: BigInt(2),
        id_temps: "2020-02-28",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(1),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(32),
        id_abonne: BigInt(32),
        id_directions: BigInt(7),
        id_produit: BigInt(2),
        id_temps: "2020-03-03",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(0),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(33),
        id_abonne: BigInt(33),
        id_directions: BigInt(7),
        id_produit: BigInt(1),
        id_temps: "2020-03-19",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(1),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(34),
        id_abonne: BigInt(34),
        id_directions: BigInt(7),
        id_produit: BigInt(2),
        id_temps: "2020-02-28",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(0),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(1),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(1),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(35),
        id_abonne: BigInt(35),
        id_directions: BigInt(7),
        id_produit: BigInt(2),
        id_temps: "2020-03-19",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(0),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(1)
      },
      {
        id_fait: BigInt(36),
        id_abonne: BigInt(36),
        id_directions: BigInt(7),
        id_produit: BigInt(2),
        id_temps: "2020-03-03",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(1),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(37),
        id_abonne: BigInt(37),
        id_directions: BigInt(7),
        id_produit: BigInt(1),
        id_temps: "2020-02-28",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(0),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(1),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(38),
        id_abonne: BigInt(38),
        id_directions: BigInt(7),
        id_produit: BigInt(2),
        id_temps: "2020-02-28",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(1),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(39),
        id_abonne: BigInt(39),
        id_directions: BigInt(7),
        id_produit: BigInt(1),
        id_temps: "2020-02-28",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(0),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(1),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      },
      {
        id_fait: BigInt(40),
        id_abonne: BigInt(40),
        id_directions: BigInt(7),
        id_produit: BigInt(1),
        id_temps: "2020-03-03",
        nombre_total_abonnes: BigInt(1),
        abonnes_actifs: BigInt(1),
        abonnes_forfait: BigInt(0),
        nouveaux_abonnes: BigInt(1),
        abonnes_factures: BigInt(0),
        abonnes_resilies: BigInt(0),
        nombre_resiliation: BigInt(0),
        nombre_modification_ps: BigInt(0),
        nombre_migration: BigInt(0),
        nombre_suspension: BigInt(0)
      }
    // Continue adding the remaining 26 entries following the same pattern...
  ];
  

export { recomendedjob, candidate }